name: Build and Run Project
on: [workflow_dispatch]
jobs:
    build-and-run:
        runs-on: ubuntu-latest
        steps:
            - name: list contents
              run: ls -al
            - name: Get code
              uses: actions/checkout@v4
            - name: list contents again
              run: ls -al
            - name: Get cmake version
              run: cmake --version             
            - name: Build Project
              run: |
                cd build
                cmake ../src/.
                make                
            - name: Build Project
              run: |
                cd build
                hello_world            
    finish:
      needs: [build-and-run]
      runs-on: ubuntu-latest
      steps:
        - name: Finish
          run: echo "Finished!"
            
